controllers/PaymentController.php
<?php
namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\payment\Payment;
use app\models\payment\PaymentDetail;

class PaymentController extends Controller
{

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['payment', 'detail'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	public function beforeAction($action)
	{
		
		if (!parent::beforeAction($action)) return false;
		
		$this->layout = 'main';
		
		return true;

	}
	
	public function actions()
	{
		
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}
	
	public function actionIndex()
	{
		
		return $this->redirect(['dashboard/index']);
		
	}
	
	public function actionPayment()
	{
		$model = new Payment();
		$data = $model->paymentList();
		return $this->render('payment', ['model'=>$model, 'payment'=>$data]);
	}
	
	public function actionDetail()
	{
		$transID = Yii::$app->request->get('id');
		$model = new PaymentDetail();
		$data = $model->paymentDetail($transID);
		return $this->renderAjax('detail',['model'=>$model,'data'=>$data]);
	}
}

views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
?>
<div class="content-wrapper body_font">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>
    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

views/layouts/footer.php
<?php
use yii\helpers\Html;

?>
<footer class="main-footer body_font">
    <div class="pull-right hidden-xs">
		<?= number_format((memory_get_usage()/1000), 0, '.', '') ?>Kb - <?= number_format(Yii::getLogger()->getElapsedTime(), 2, '.', '') ?>s - <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2019 <a href="http://ajiraconnect.com">Ajira Connect</a>.</strong> All rights
    reserved.
</footer>

views/layouts/header.php
<?php
use yii\helpers\Html;
?>


<header class="main-header">
    <?= Html::a('<span class="logo-mini">AC</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu">
            <span class="fas fa-bars"></span>
        </a>
        <div class="navbar-custom-menu dropdown ">
            <ul class="nav navbar-nav ">
                <li class="user user-menu">
                    <ul class="dropdown-menu" role="menu">

                    </ul>
                </li>
                <li>
                  <a href="#" data-toggle="control-sidebar"><i class="fas fa-gears"></i></a>
                </li>
                <li class="user-footer">
                          <?= Html::a(
                              'Sign out',
                              ['/site/logout'],
                              ['data-method' => 'post', 'class' => '']
                          ) ?>
                  </li>
            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<aside class="main-sidebar body_font">
    <section class="sidebar">
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <?= app\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Main', 'options' => ['class' => 'header']],
					['label' => 'Dashboard', 'icon' => 'user-circle', 'url' => ['/dashboard']],
                    ['label' => 'Request', 'icon' => 'user-circle', 'url' => ['/request']],
                    ['label' => 'Professionals', 'icon' => 'user-circle', 'url' => ['/professional']],
                    ['label' => 'Customers', 'icon' => 'user-md', 'url' => ['/customer']],
                    ['label' => 'Services', 'icon' => 'users', 'url' => ['/services']],
                    ['label' => 'Payment', 'icon' => 'credit-card', 'url' => ['/payment/payment']],
                    ['label' => 'Receipts', 'icon' => 'file', 'url' => ['/request']],
                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                ],
            ]
        ) ?>
    </section>
</aside>

views/layouts/main-login.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		<link href="<?= Yii::getAlias('@web') ?>/css/AdminLTE.css" rel="stylesheet">
		<link href="<?= Yii::getAlias('@web') ?>/css/skins/_all-skins.css" rel="stylesheet">
		<link href="<?= Yii::getAlias('@web') ?>/css/site.css" rel="stylesheet">
	</head>
	<body class="login-page">
		<?php $this->beginBody() ?>
			<?= $content ?>
		<?php $this->endBody() ?>
	<script src="<?= Yii::getAlias('@web') ?>/js/adminlte.min.js"></script>
	</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use app\assets\AppAsset;
use yii\helpers\Html;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>"/>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
		<link rel="icon" href="/favicon.ico">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
		<link href="<?= Yii::getAlias('@web') ?>/css/AdminLTE.css" rel="stylesheet">
		<link href="<?= Yii::getAlias('@web') ?>/css/skins/_all-skins.css" rel="stylesheet">
		<link href="<?= Yii::getAlias('@web') ?>/css/site.css" rel="stylesheet">
	</head>
	<body class="hold-transition skin-blue sidebar-mini">
		<?php $this->beginBody() ?>
		<div class="wrapper">
			<?= $this->render('header.php') ?>
			<?= $this->render('left.php') ?>
			<?= $this->render('content.php',['content' => $content]) ?>
			<?= $this->render('footer.php') ?>
		</div>
		<?php $this->endBody() ?>
	<script src="<?= Yii::getAlias('@web') ?>/js/adminlte.min.js"></script>
	</body>
</html>
<?php $this->endPage() ?>